# Generated by Django 5.2.12 on 2026-04-02 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Alerts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chatbotlogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255)),
                ('response', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ChatbotLogs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Predictions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_alarm', models.IntegerField()),
                ('confidence_score', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Predictions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SensorData1Tbl',
            fields=[
                ('timestamp', models.DateTimeField()),
                ('gas_level', models.FloatField()),
                ('temperature', models.FloatField()),
                ('pressure', models.FloatField()),
                ('smoke_level', models.FloatField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('alarm', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': '_Sensor_Data1TBL',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Userinputsensordata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('gas_level', models.FloatField()),
                ('temperature', models.FloatField()),
                ('pressure', models.FloatField()),
                ('smoke_level', models.FloatField()),
                ('alarm', models.IntegerField()),
            ],
            options={
                'db_table': 'UserInputSensorData',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Users',
                'managed': False,
            },
        ),
    ]
