# Generated by Django 5.2.12 on 2026-04-02 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alerts',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='chatbotlogs',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='predictions',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='sensordata1tbl',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='userinputsensordata',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'managed': True},
        ),
    ]
